In [41]:
### paquetes de impotacion y manejo de datos
import pandas as pd
import numpy as np

# ### paquetes de graficos
import matplotlib.pyplot as plot
# from scipy import stats

# ######  paquetes de analitica de datos
# from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [40]:
archivo = 'AirQualityUCI.csv'
df = pd.read_csv(archivo, sep=';')
df = df.replace(';;', ';', regex=True)
df['CO(GT)'] = df['CO(GT)'].str.replace(',', '.')
df['C6H6(GT)'] = df['C6H6(GT)'].str.replace(',', '.')
df['T'] = df['T'].str.replace(',', '.')
df['RH'] = df['RH'].str.replace(',', '.')
df['AH'] = df['AH'].str.replace(',', '.')
df = df.drop(df.columns[-1],axis=1)
df = df.drop(df.columns[-2],axis=1)
df=df.dropna()
df

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,04/04/2005,10.00.00,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11.00.00,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12.00.00,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13.00.00,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14.00.00,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [43]:
column_name = ['Date ','Time','CO(GT)','PT08.S1(CO)','NMHC(GT)','C6H6(GT)','PT08.S2(NMHC)','NOx(GT)','PT08.S3(NOx)','NO2(GT)','PT08.S4(NO2)','PT08.S5(O3)','T','RH','AH']
numeric_columns = ['CO(GT)','PT08.S1(CO)','NMHC(GT)','C6H6(GT)','PT08.S2(NMHC)','NOx(GT)','PT08.S3(NOx)','NO2(GT)','PT08.S4(NO2)','PT08.S5(O3)','T','RH','AH']

for column in numeric_columns:
    df[column]=pd.to_numeric(df[column], errors='coerce')
    
df

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,04/04/2005,10.00.00,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11.00.00,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12.00.00,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13.00.00,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14.00.00,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [56]:
def sin_atipicos(df, numeric_columns):
    cleaned_df = df.copy()
    indices = pd.DataFrame()
    filas_atipicas = set()
    for columna in numeric_columns:
        datos = df[columna]
        np.int_(datos)
        q1 = np.percentile(datos, 25)
        
        q3 = np.percentile(datos, 75)
        iqr = q3 - q1
        limite_inferior = q1 - 1.5 * iqr
        limite_superior = q3 + 1.5 * iqr
        for index, value in enumerate(datos):
            if value < limite_inferior or limite_superior < value:
                filas_atipicas.add(index)
                indice=df.iloc[index]
                indices=indices.append([indice])
            
                
    filas_atipicas = list(filas_atipicas)
    filas_atipicas.sort()
    cleaned_df = cleaned_df.drop(index=filas_atipicas)
    return cleaned_df, indices

cleaned_df, filasatipicas = sin_atipicos(df, numeric_columns)

cleaned_df

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
184,18/03/2004,10.00.00,4.5,1617.0,-200.0,21.3,1333.0,349.0,686.0,150.0,2010.0,1819.0,17.8,40.5,0.8210
185,18/03/2004,11.00.00,2.8,1473.0,-200.0,14.3,1127.0,224.0,831.0,152.0,1752.0,1568.0,20.8,34.4,0.8365
186,18/03/2004,12.00.00,2.2,1379.0,-200.0,12.5,1068.0,171.0,899.0,139.0,1663.0,1374.0,23.8,28.2,0.8219
187,18/03/2004,13.00.00,2.2,1385.0,-200.0,12.2,1056.0,149.0,891.0,133.0,1648.0,1268.0,24.2,28.7,0.8515
188,18/03/2004,14.00.00,2.3,1379.0,-200.0,13.1,1087.0,137.0,901.0,126.0,1660.0,1144.0,25.2,24.9,0.7829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,04/04/2005,10.00.00,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11.00.00,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12.00.00,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13.00.00,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14.00.00,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [57]:
filasatipicas

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
10,11/03/2004,04.00.00,-200.0,1011.0,14.0,1.3,527.0,21.0,1818.0,34.0,1197.0,445.0,10.1,60.5,0.7465
25,11/03/2004,19.00.00,6.9,1776.0,461.0,27.4,1488.0,383.0,702.0,172.0,2333.0,1704.0,9.7,69.3,0.8319
26,11/03/2004,20.00.00,6.1,1640.0,401.0,24.0,1404.0,351.0,743.0,165.0,2191.0,1654.0,9.6,67.8,0.8133
34,12/03/2004,04.00.00,-200.0,831.0,10.0,1.1,506.0,21.0,1893.0,32.0,1134.0,384.0,6.1,65.9,0.6248
39,12/03/2004,09.00.00,-200.0,1545.0,-200.0,22.1,1353.0,-200.0,767.0,-200.0,2058.0,1588.0,9.2,56.2,0.6561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8111,11/02/2005,17.00.00,6.6,-200.0,-200.0,-200.0,-200.0,1227.0,-200.0,326.0,-200.0,-200.0,-200.0,-200.0,-200.0000
8112,11/02/2005,18.00.00,6.5,-200.0,-200.0,-200.0,-200.0,1061.0,-200.0,284.0,-200.0,-200.0,-200.0,-200.0,-200.0000
8113,11/02/2005,19.00.00,7.1,-200.0,-200.0,-200.0,-200.0,1075.0,-200.0,289.0,-200.0,-200.0,-200.0,-200.0,-200.0000
8114,11/02/2005,20.00.00,4.9,-200.0,-200.0,-200.0,-200.0,641.0,-200.0,215.0,-200.0,-200.0,-200.0,-200.0,-200.0000
8777,11/03/2005,11.00.00,3.0,-200.0,-200.0,-200.0,-200.0,812.0,-200.0,235.0,-200.0,-200.0,-200.0,-200.0,-200.0000

In [58]:
matriz_c = cleaned_df.corr()
matriz_c

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
CO(GT),1.000000,0.825238,NaN,0.897716,0.890678,0.736020,-0.751171,0.632304,0.536160,0.802646,0.098319,-0.028029,0.076061
PT08.S1(CO),0.825238,1.000000,NaN,0.836470,0.842674,0.685111,-0.855462,0.566153,0.574957,0.868828,0.098117,0.129680,0.202078
NMHC(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C6H6(GT),0.897716,0.836470,NaN,1.000000,0.988320,0.618527,-0.761795,0.518589,0.735198,0.814160,0.319310,-0.134951,0.243314
PT08.S2(NMHC),0.890678,0.842674,NaN,0.988320,1.000000,0.623820,-0.798224,0.541232,0.738070,0.826075,0.338349,-0.147861,0.250780
NOx(GT),0.736020,0.685111,NaN,0.618527,0.623820,1.000000,-0.702389,0.730964,0.066400,0.746371,-0.312629,0.199524,-0.220892
PT08.S3(NOx),-0.751171,-0.855462,NaN,-0.761795,-0.798224,-0.702389,1.000000,-0.599358,-0.476510,-0.832124,-0.086145,-0.129571,-0.213684
NO2(GT),0.632304,0.566153,NaN,0.518589,0.541232,0.730964,-0.599358,1.000000,-0.009912,0.618047,-0.227638,-0.145998,-0.428141
PT08.S4(NO2),0.536160,0.574957,NaN,0.735198,0.738070,0.066400,-0.476510,-0.009912,1.000000,0.481734,0.688568,-0.079154,0.742182
PT08.S5(O3),0.802646,0.868828,NaN,0.814160,0.826075,0.746371,-0.832124,0.618047,0.481734,1.000000,-0.013434,0.138070,0.091967
T,0.098319,0.098117,NaN,0.319310,0.338349,-0.312629,-0.086145,-0.227638,0.688568,-0.013434,1.000000,-0.564230,0.665401
RH,-0.028029,0.129680,NaN,-0.134951,-0.147861,0.199524,-0.129571,-0.145998,-0.079154,0.138070,-0.564230,1.000000,0.171496
AH,0.076061,0.202078,NaN,0.243314,0.250780,-0.220892,-0.213684,-0.428141,0.742182,0.091967,0.665401,0.171496,1.000000

In [64]:
X= cleaned_df[['PT08.S1(CO)','C6H6(GT)','CO(GT)','PT08.S5(O3)','PT08.S3(NOx)']]
Y=cleaned_df['PT08.S2(NMHC)']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size = 0.7)
modelo2 = LinearRegression()
modelo2.fit(X=np.array(X_train),y=Y_train)
predicciones = modelo2.predict(X= np.array(X_test))
r2 = r2_score(y_true= Y_test, y_pred= predicciones)
print("El valor de r2 es:",r2)

El valor de r2 es: 0.981636767991027

In [65]:
X= cleaned_df[['PT08.S2(NMHC)','C6H6(GT)','CO(GT)','PT08.S5(O3)','PT08.S3(NOx)']]
Y=cleaned_df['PT08.S1(CO)']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size = 0.7)
modelo2 = LinearRegression()
modelo2.fit(X=np.array(X_train),y=Y_train)
predicciones = modelo2.predict(X= np.array(X_test))
r2 = r2_score(y_true= Y_test, y_pred= predicciones)
print("El valor de r2 es:",r2)

El valor de r2 es: 0.8441274274291141

In [67]:
df['NMHC(GT)']

0       150.0
1       112.0
2        88.0
3        80.0
4        51.0
        ...
9352   -200.0
9353   -200.0
9354   -200.0
9355   -200.0
9356   -200.0
Name: NMHC(GT), Length: 9357, dtype: float64